//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int bill_id { get; set; }
        public string sub_total { get; set; }
        public Nullable<float> discount { get; set; }
        public Nullable<float> total { get; set; }
        public Nullable<int> staff_id { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
