//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class expens
    {
        public int ext_id { get; set; }
        public string ext_category { get; set; }
        public Nullable<System.DateTime> ext_date { get; set; }
        public Nullable<float> ext_amount { get; set; }
    }
}
