//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class sup_mobile_no
    {
        public int sup_id { get; set; }
        public string sup_mobile_no1 { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
