//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;

    public partial class customer
    {
        public long cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string cust_mobileno { get; set; }
        public virtual List<customer> customerv {get;set;}
    }
}
