//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        public int med_barcode { get; set; }
        public string med_name { get; set; }
        public Nullable<float> med_purshase_price { get; set; }
        public Nullable<float> med_selling_price { get; set; }
        public Nullable<float> med_quantity { get; set; }
        public string med_generic_name { get; set; }
        public string med_type { get; set; }
        public Nullable<System.DateTime> med_ex_date { get; set; }
        public string med_location { get; set; }
        public Nullable<int> sup_id { get; set; }
    
        public virtual med_category med_category { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
