//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pharmacydbEntities : DbContext
    {
        public pharmacydbEntities()
            : base("name=pharmacydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bills { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<expens> expenses { get; set; }
        public DbSet<med_category> med_category { get; set; }
        public DbSet<medicine> medicines { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<sup_mobile_no> sup_mobile_no { get; set; }
        public DbSet<supplier> suppliers { get; set; }
    }
}
