//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.bills = new HashSet<bill>();
        }
    
        public int staff_id { get; set; }
        public string staff_name { get; set; }
        public Nullable<float> staff_salary { get; set; }
        public Nullable<int> staff_phone { get; set; }
        public string staff_address { get; set; }
        public string staff_email { get; set; }
        public string staff_role { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
    }
}
