//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.medicines = new HashSet<medicine>();
        }
    
        public int sup_id { get; set; }
        public string sup_name { get; set; }
        public string sup_email { get; set; }
        public string sup_address { get; set; }
    
        public virtual ICollection<medicine> medicines { get; set; }
        public virtual sup_mobile_no sup_mobile_no { get; set; }
    }
}
